# Site variables
title: Sebastian Göttschkes | Freelance Developer, Consultant and Speaker
description: Sebastian Göttschkes is a freelance Web Developer from Vienna specialized in PHP, Python and Dart. He also supports clients in getting up to speed with Vagrant and Ansible.

# Build settings
exclude: ['Rakefile', 'README.md', 'Vagrantfile']
timezone: Europe/Vienna
encoding: utf-8

# Serve settings
host: 0.0.0.0
port: 4000
